TARGET = stattracker

CPU_FREQ = 16000000

C_FILES = \
	main.c \
	../../include/color_utils.c \
	../../include/bitbang.c \
	../../include/adc.c \
	../../include/debug.c

ASM_FILES = \
	bitbang_asm.asm

pre-flash:
	

include ../Makefile.include
